// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notes.Infrastructure.DatabaseContext;

#nullable disable

namespace Notes.Infrastructure.Migrations
{
    [DbContext(typeof(NoteDatabaseContext))]
    partial class NoteDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Notes.Domain.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "TestContent",
                            DateCreated = new DateTime(2024, 3, 24, 12, 58, 21, 33, DateTimeKind.Local).AddTicks(6710),
                            Title = "TestTitle"
                        },
                        new
                        {
                            Id = 2,
                            Content = "SecondContent",
                            DateCreated = new DateTime(2024, 3, 24, 12, 58, 21, 33, DateTimeKind.Local).AddTicks(6750),
                            Title = "SecondTestTitle"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
